backend:
  - changed-files:
      - any-glob-to-any-file:
          - "backend/**"

frontend:
  - changed-files:
      - any-glob-to-any-file:
          - "frontend/**"

refactor:
  - changed-files:
      - any-glob-to-any-file:
          - "backend/src/main/java/com/company/evaluation/**/service/**"
          - "backend/src/main/java/com/company/evaluation/**/controller/**"
          - "frontend/src/**"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**"

config:
  - changed-files:
      - any-glob-to-any-file:
          - "backend/src/main/resources/**"
          - "frontend/**/vite.config.*"
