name: Refactor
description: 구조/코드 리팩토링 작업 티켓
labels: [refactor]
body:
  - type: textarea
    attributes:
      label: 배경
      description: 왜 이 리팩토링이 필요한가요?
    validations:
      required: true
  - type: textarea
    attributes:
      label: 작업 범위
      description: 파일/패키지/모듈 단위로 정리
    validations:
      required: true
  - type: textarea
    attributes:
      label: 완료 기준
      description: Done 정의(테스트/빌드/문서)
    validations:
      required: true


