spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_eval?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: app
    password: change-me
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

logging:
  level:
    com.company.evaluation: info


